// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHJcjenxuvXqzlLg-fGSIcjc3m7fEs_ds',
    appId: '1:557599764333:web:3ef267c8fafe1365b77464',
    messagingSenderId: '557599764333',
    projectId: 'chat-app-95a49',
    authDomain: 'chat-app-95a49.firebaseapp.com',
    storageBucket: 'chat-app-95a49.appspot.com',
    measurementId: 'G-0GK6D4LRHQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_rkAAhzFtfdQGRU3sWcorCwkfKE_vS80',
    appId: '1:557599764333:android:ad38f3a9dccb4445b77464',
    messagingSenderId: '557599764333',
    projectId: 'chat-app-95a49',
    storageBucket: 'chat-app-95a49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh4iYn7C4-9dpj7c3Bo_xhBDuUUmVdkxk',
    appId: '1:557599764333:ios:80f96170d2793540b77464',
    messagingSenderId: '557599764333',
    projectId: 'chat-app-95a49',
    storageBucket: 'chat-app-95a49.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh4iYn7C4-9dpj7c3Bo_xhBDuUUmVdkxk',
    appId: '1:557599764333:ios:80f96170d2793540b77464',
    messagingSenderId: '557599764333',
    projectId: 'chat-app-95a49',
    storageBucket: 'chat-app-95a49.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHJcjenxuvXqzlLg-fGSIcjc3m7fEs_ds',
    appId: '1:557599764333:web:260eda8b3d9e4067b77464',
    messagingSenderId: '557599764333',
    projectId: 'chat-app-95a49',
    authDomain: 'chat-app-95a49.firebaseapp.com',
    storageBucket: 'chat-app-95a49.appspot.com',
    measurementId: 'G-2NP4QZ1JCT',
  );
}
